- name: redis
  hosts: redis
  become: yes
  tasks:
  - name: install remirepo
    ansible.builtin.dnf:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: present
      disable_gpg_check: true

  - name: enabled redis package
    ansible.builtin.command: dnf module enable redis:remi-6.2 -y

  - name: install redis
    ansible.builtin.dnf:
      name: redis
      state: present

  - name: service access
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: enabled and start the service
    ansible.builtin.service:
      enabled: yes
      state: restarted

  



